### Проверка работы API
GET http://localhost:8083/api/test/ping

### Логин
POST http://localhost:8083/api/auth/login
Content-Type: application/json

{
  "email": "admin@mail.ru",
  "password": "123456789"
}
### Логин
POST http://localhost:8083/api/auth/login
Content-Type: application/json

{
"email": "1@test.ru",
"password": "123456789"
}
### Получить текущего пользователя
GET http://localhost:8083/api/users/me
Authorization: Bearer <ваш_токен>

### Получить всех пользователей (только ADMIN)
GET http://localhost:8083/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzc0NjE0NjkzLCJleHAiOjE3NzQ3MDEwOTN9.g-DAVEg-7cAYXdParzB67HRHN80PXBKwckJMGqbw0tk

###
GET http://localhost:8083/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzc0NjE0NjkzLCJleHAiOjE3NzQ3MDEwOTN9.g-DAVEg-7cAYXdParzB67HRHN80PXBKwckJMGqbw0tk

### Регистрация нового пользователя
POST http://localhost:8083/api/auth/register
Content-Type: application/json

{
  "email": "newuser@test.com",
  "password": "password123",
  "firstName": "New",
  "lastName": "User",
  "phone": "+79001234567",
  "role": "ENGINEER"
}

### Регистрация нового админа
POST http://localhost:8083/api/auth/register
Content-Type: application/json

{
  "email": "newadmin@test.com",
  "password": "admin123",
  "firstName": "New",
  "lastName": "Admin",
  "phone": "+79001234568",
  "role": "ADMIN",
  "secretKey": "Abra-Cadabra!"
}
